class IMAGE_ORIENTATION:
    IMAGE_ORIENTATION_ORIGIN_TOP_LEFT = 0
    IMAGE_ORIENTATION_ORIGIN_TOP_RIGHT = 1
    IMAGE_ORIENTATION_ORIGIN_BOTTOM_RIGHT = 2
    IMAGE_ORIENTATION_ORIGIN_BOTTOM_LEFT = 3
