"""Leica SDK enums.

Using IntEnum for type safety while maintaining compatibility with SDK int parameters.
Values from Leica AHM SDK 2020.3.3.10693.
"""

from enum import IntEnum


class TID(IntEnum):
    """Type IDs for microscope units.

    Values from ahwmic.h (SDK 2020.3.3.10693).
    """

    # Core types (0x1000+)
    MICROSCOPE = 0x1000
    MICROSCOPE_UNIT = 0x1001
    MICROSCOPE_MOTORIZED_UNIT = 0x1002
    MICROSCOPE_CODED_UNIT = 0x1003
    MICROSCOPE_NOSEPIECE = 0x1004
    MICROSCOPE_ZDRIVE = 0x1005
    MICROSCOPE_TL_AXIS = 0x1006
    MICROSCOPE_IL_AXIS = 0x1007
    MICROSCOPE_IL_TURRET = 0x1008

    # Diaphragms and condenser
    MICROSCOPE_CONDENSER = 0x100B
    MICROSCOPE_CONDENSER_TURRET = 0x100C
    MICROSCOPE_STAGE = 0x1010

    # Shutters and lamp
    MICROSCOPE_SHUTTER = 0x1013
    MICROSCOPE_DIC_TURRET = 0x1014
    MICROSCOPE_LAMP = 0x1017
    MICROSCOPE_TL_IL_LAMP_SWITCH = 0x1018

    # Axes
    MICROSCOPE_X_UNIT = 0x101A
    MICROSCOPE_Y_UNIT = 0x101B
    MICROSCOPE_Z_UNIT = 0x101C

    # Light axis units
    MICROSCOPE_INCIDENT_LIGHT_UNIT = 0x1023
    MICROSCOPE_TRANSMITTED_LIGHT_UNIT = 0x1024
    MICROSCOPE_TL_SHUTTER = 0x1025
    MICROSCOPE_IL_SHUTTER = 0x1026

    # Diaphragms (0x102C+)
    MICROSCOPE_TL_APERTURE_DIAPHRAGM = 0x102C
    MICROSCOPE_TL_FIELD_DIAPHRAGM = 0x102D
    MICROSCOPE_IL_APERTURE_DIAPHRAGM = 0x102E
    MICROSCOPE_IL_FIELD_DIAPHRAGM = 0x102F
    MICROSCOPE_IL_ATTENUATOR = 0x1030
    MICROSCOPE_PORTS = 0x1031
    MICROSCOPE_MANUAL_UNIT = 0x1033

    # Sequencer
    MICROSCOPE_SEQUENCER = 0x1069
    MICROSCOPE_SEQUENCER_TIMESTAMPS = 0x1086
    MICROSCOPE_CAMERA_INTERFACE = 0x1087

    # LED units (0x107D+)
    MICROSCOPE_ARCLIGHT_UNIT = 0x107D
    MICROSCOPE_ARCLIGHT_INTENSITY = 0x107E
    MICROSCOPE_ARCLIGHT_SHUTTER = 0x107F
    MICROSCOPE_ARCLIGHT_SCENE = 0x1080
    MICROSCOPE_RINGLIGHT_UNIT = 0x1081
    MICROSCOPE_RINGLIGHT_INTENSITY = 0x1082
    MICROSCOPE_RINGLIGHT_SHUTTER = 0x1083
    MICROSCOPE_RINGLIGHT_SCENE = 0x1084

    # Lamp units
    MICROSCOPE_TL_LAMP = 0x1078
    MICROSCOPE_IL_LAMP = 0x1077
    MICROSCOPE_LIGHT_UNIT = 0x1055


class IID(IntEnum):
    """Interface IDs for unit capabilities.

    Values from ahwbasic.h and ahwmic.h (SDK 2020.3.3.10693).
    """

    # Core interfaces (0x10+)
    IID_DRIVER_INFO = 0x10
    IID_SESSION = 0x11
    IID_INIT_STATE = 0x14

    # Basic interfaces (0x100+)
    IID_BASIC_CONTROL_VALUE = 0x100
    IID_BASIC_CALIBRATION = 0x101
    IID_AUTO_CALIBRATION = 0x102
    IID_BASIC_CONFIGURATION = 0x103
    IID_PROPERTIES = 0x104
    IID_SNAPSHOTS = 0x105
    IID_EVENT_SOURCE = 0x106
    IID_DELTA_CONTROL_VALUE = 0x107
    IID_BASIC_CONTROL_VALUE_VELOCITY = 0x108
    IID_LIMIT_CONTROL_VALUE = 0x109
    IID_BASIC_CONTROL_STATE = 0x10A
    IID_HALT_CONTROL_VALUE = 0x10B
    IID_DIRECTED_CONTROL_VALUE_ASYNC = 0x10C
    IID_BASIC_CONTROL_VALUE_ASYNC = 0x10D
    IID_FACTORY_SETTINGS = 0x10E
    IID_ADVANCED_EVENT_SOURCE = 0x10F
    IID_DEFINED_CONTROL_VALUES = 0x110
    IID_BASIC_CONTROL_VALUE_SPECIAL = 0x111
    IID_PROPERTIES_UI = 0x112
    IID_ALTERNATING_CONTROL_UNITS = 0x113
    IID_DIRECTED_CONTROL_VALUE_ASYNC_VELOCITY = 0x114
    IID_LIMIT_SWITCHES = 0x115
    IID_LOGGING = 0x116
    IID_BASIC_CONTROL_VALUE_TIMING = 0x117
    IID_BASIC_CONTROL_VALUE_SETS = 0x118
    IID_BASIC_CONTROL_VALUE_HYSTERESIS_CORRECTED = 0x119
    IID_PROPERTY_ID_NAMES = 0x11A
    IID_DELTA_CONTROL_VALUE_ASYNC = 0x11B
    IID_BASIC_CONTROL_VALUE_ACCELERATION = 0x11C

    # Microscope-specific (0x1000+)
    IID_MICROSCOPE_CONTRASTING_METHODS = 0x1000
    IID_MICROSCOPE_MEMORY = 0x1003
    IID_MICROSCOPE_SHEARING = 0x1006
    IID_MICROSCOPE_CALIBRATION_TABLE = 0x1010
    IID_MICROSCOPE_SCENE_SEQUENCE = 0x1011
    IID_MICROSCOPE_SEQUENCER_TIMESTAMPS = 0x1012
    IID_MICROSCOPE_SEQUENCER_CONTROL = 0x1013
    IID_MICROSCOPE_EXACT_ZFOCUS = 0x1017
    IID_MICROSCOPE_SEQUENCER_TRIGGERING_SETUP = 0x101A
    IID_MICROSCOPE_DVM_AUTOFOCUS = 0x101C


class EMetricsId(IntEnum):
    """Metrics IDs for unit conversion."""

    METRICS_NONE = 0
    METRICS_MICRONS = 1
    METRICS_VOLTAGE = 2
    METRICS_DIMENSIONLESS = 3
    METRICS_LIGHTYEARS = 4
    METRICS_MACH = 5
    METRICS_MICRONS_PER_SECOND = 6
    METRICS_DEGREES_KELVIN = 7
    METRICS_LINEPAIR_PER_MILLIMETERS = 8
    METRICS_DEGREES = 9
    METRICS_DEGREES_CELSIUS = 10
    METRICS_MICRONS_PER_SECOND_SQUARED = 11
    METRICS_NANOMETERS = 12
    METRICS_NATIVE = 13


class MoveState(IntEnum):
    """State of an async move operation."""

    PENDING = 0
    IN_PROGRESS = 1
    COMPLETE = 2
    CANCELLED = 3
    ERROR = 4


class EState(IntEnum):
    """SDK AsyncResult.EState values (from ahwbasic.h)."""

    INPROGRESS = 0  # Move in progress
    COMPLETED = 1  # Move completed successfully
    STOPPED = 2  # Move was halted
    OVERRIDDEN = 3  # Move was overridden by another


class EErrorClass(IntEnum):
    """SDK error classification."""

    UNDEF = -1
    GENERAL_ERROR = 0
    COMMUNICATION_ERROR = 1
    HARDWARE_ERROR = 2
    INTERNAL_ERROR = 3
    SNAPSHOTS_ERROR = 4


class EErrorCode(IntEnum):
    """SDK error codes."""

    UNDEF = -1
    UNIT_NOT_INITIALIZED = 0
    IID_INVALID = 1
    PARAMETER_INVALID = 2
    HARDWARE_FAILURE = 3
    TIMEOUT = 4
    UNIT_NOT_DETECTED = 5
    UNSUPPORTED = 6
    ACCESS_INVALID = 7
    MANUAL_INTERACTION_NEEDED = 8
    LOADING_DRIVER_FAILED = 9
    OUT_OF_MEMORY = 10
    INVALID_OPERATION = 11
    FILE_NOT_FOUND = 12
    FILE_READ = 13
    FILE_WRITE = 14
    CONNECTION_LOST = 15


class EEventType(IntEnum):
    """SDK event type identifiers."""

    INTERFACE_STATE_CHANGED = 0x11
    VALUE_CHANGED = 0x100
    PROPERTY_CHANGED = 0x101
    VALUE_CHANGED_STRING = 0x102
    PROPERTY_INFO_CHANGED = 0x103


# ============================================================================
# UCAPI (Camera) Enums
# ============================================================================


class UCAPI_TID(IntEnum):
    """Type IDs for UCAPI camera units."""

    UCAPI_DRIVER = 16384
    UCAPI_CAMERA = 16385
    UCAPI_CAMERA_SENSOR = 16386


class UCAPI_IID(IntEnum):
    """Interface IDs for UCAPI camera capabilities."""

    IID_IMAGE_ACQUISITION = 16384
    IID_IMAGE_SEQUENCE_ACQUISITION = 16385
    IID_ACQUISITION_INFORMATION = 16386
    IID_IMAGE_FORMAT_INFORMATION = 16387
    IID_ONE_SHOT_WHITE_BALANCE = 16388
    IID_WHITE_SHADING_REFERENCE_CREATOR = 16389
    IID_ONE_SHOT_BLACK_BALANCE = 16390
    IID_PROPERTY_DEPENDENCY_INFORMATION = 16391


class UCAPI_PROP(IntEnum):
    """Property IDs for UCAPI camera settings."""

    # Sensor info
    PROP_SERIAL_NUMBER = 16384
    PROP_FIRMWARE_HEAD_VERSION = 16385
    PROP_VERSION_INFO = 16386
    PROP_SENSOR_XRESOLUTION = 16387
    PROP_SENSOR_YRESOLUTION = 16388
    PROP_PHYSICAL_PIXEL_XSIZE = 16389
    PROP_PHYSICAL_PIXEL_YSIZE = 16390
    PROP_LOGICAL_XRESOLUTION = 16391
    PROP_LOGICAL_YRESOLUTION = 16392
    PROP_LOGICAL_CENTRE_XOFFSET = 16393
    PROP_LOGICAL_CENTRE_YOFFSET = 16394
    PROP_LOGICAL_PIXEL_XSIZE = 16395
    PROP_LOGICAL_PIXEL_YSIZE = 16396

    # Exposure and gain
    PROP_EXPOSURE_TIME = 16399
    PROP_GAIN = 16401
    PROP_GAIN_RED = 16402
    PROP_GAIN_GREEN = 16403
    PROP_GAIN_BLUE = 16404
    PROP_EMGAIN = 16400

    # Auto brightness
    PROP_AUTO_BRIGHTNESS_ENABLED = 16405
    PROP_AUTO_BRIGHTNESS_LEVEL = 16406
    PROP_AUTO_BRIGHTNESS_ROI = 16407
    PROP_AUTO_BRIGHTNESS_ROI_ENABLED = 16408

    # Image processing
    PROP_COLOUR_SATURATION = 16409
    PROP_GAMMA_LEVEL = 16417
    PROP_BLACK_LEVEL = 16418
    PROP_WHITE_LEVEL = 16419
    PROP_SHARPENING_LEVEL = 16423
    PROP_NOISE_REDUCTION_LEVEL = 16463
    PROP_NOISE_REDUCTION_ENABLED = 16464

    # Binning and format
    PROP_BINNING_LEVEL = 16410
    PROP_PIXEL_DEPTH = 16413
    PROP_PIXEL_TYPE = 16414
    PROP_READOUT_REGION = 16415
    PROP_READOUT_REGIONS = 16416
    PROP_CAPTURE_FORMAT_ID = 16428
    PROP_STREAMING_FORMAT_ID = 16429

    # Triggering
    PROP_IMAGE_TRIGGER_MODE = 16397
    PROP_TRIGGER_POLARITY = 16398
    PROP_MIN_TRIGGER_INTERVAL = 16451

    # Timing
    PROP_IMAGE_READOUT_TIME = 16452
    PROP_ACQUISITION_TIMEOUT = 16446
    PROP_AUTO_ACQUISITION_TIMEOUT_ENABLED = 16447
    PROP_IMAGE_TIMESTAMP = 16495
    PROP_ACQUISITION_FRAMERATE = 16502
    PROP_ACQUISITION_FRAMERATE_ENABLED = 16503

    # Mirroring
    PROP_XMIRRORING_ENABLED = 16424
    PROP_YMIRRORING_ENABLED = 16425

    # White balance
    PROP_CONTINUOUS_WHITE_BALANCE_ENABLED = 16432
    PROP_WHITE_SHADING_CORRECTION_ENABLED = 16438

    # Temperature
    PROP_TEMPERATURE = 16448
    PROP_TARGET_TEMPERATURE = 16449
    PROP_FAN_SPEED = 16450
    PROP_FAN_SPEED_LEVEL = 16431

    # --- Color pipeline (host-side ISP in ucBgapi.dll) ---
    # The K5C streams raw Bayer to the host; debayer, colour matrix (CCM),
    # saturation, gamma, and levels are applied by the driver. These
    # properties control that pipeline. IDs from ucapi.h 2023.3 (deployed
    # ucBgapi.dll is 1.15.0.12509, the 2023.3 build).
    PROP_COLOUR_TEMPERATURE = 16462  # CCM selector (enum: UserDefinedMatrix/4500K/5800K/6600K)
    PROP_SATURATION_CORRECTION = 16439
    PROP_HUE_CORRECTION = 16440
    PROP_SHARPENING_ENABLED = 16494
    PROP_AUTO_GAMMA_LEVEL_ENABLED = 16420
    PROP_AUTO_BLACK_LEVEL_ENABLED = 16421
    PROP_AUTO_WHITE_LEVEL_ENABLED = 16422

    # --- Probe-only IDs (2026-08-06 camera-raw investigation) ---
    # Full UCAPI 2023.3 property space not yet mirrored above, added for
    # scripts/experiments/probe_camera_pipeline.py. Prune whichever of
    # these the probe shows the K5C does not implement (see
    # /tmp/camera_raw_summary.md).
    PROP_BINNED_BRIGHTNESS_CORRECTION_ENABLED = 16411
    PROP_READOUT_SPEED = 16412
    PROP_IMAGE_AVERAGING_MODE = 16426
    PROP_IMAGE_AVERAGING_COUNT = 16427
    PROP_ACQUISITION_MODE = 16430
    PROP_CONTINUOUS_WHITE_BALANCE_ROI = 16433
    PROP_CONTINUOUS_WHITE_BALANCE_ROI_ENABLED = 16434
    PROP_FOCUS_SCORE_ROI = 16435
    PROP_FOCUS_SCORE_ROI_ENABLED = 16436
    PROP_WHITE_SHADING_REFERENCE_FILE = 16437
    PROP_AVERAGE_COLOUR_ROI = 16441
    PROP_AVERAGE_COLOUR_ROI_ENABLED = 16442
    PROP_PSEUDO_COLOUR_WAVELENGTH = 16443
    PROP_BLACK_BALANCE_LEVEL = 16444
    PROP_BLACK_BALANCE_ENABLED = 16445
    PROP_NIR_MODE_ENABLED = 16453
    PROP_CAMERA_SDK_VERSION = 16454
    PROP_READOUT_OVERLAP_ENABLED = 16455
    PROP_HOTPIXEL_EXPOSURE_THRESHOLD = 16457
    PROP_HOTPIXEL_INTENSITY_THRESHOLD = 16458
    PROP_ENHANCED_ACQUISITION_MODE = 16474
    PROP_HDR_MODE = 16475
    PROP_HDR_CONTRAST = 16476
    PROP_HDR_BRIGHTNESS = 16480
    PROP_DISPLAY_NAME = 16481
    PROP_PIXEL_ALIGNMENT = 16482
    PROP_DECIMATION_MODE = 16483
    PROP_ACCEPT_UNEXPECTED_FORMAT = 16485
    PROP_SCAN_COUNT = 16486
    PROP_CUSTOM_FORMAT_XRESOLUTION = 16487
    PROP_CUSTOM_FORMAT_YRESOLUTION = 16488
    PROP_EXPECTED_CONNECTION_INTERFACE = 16489
    PROP_DETECTED_CONNECTION_INTERFACE = 16490
    PROP_AUTO_EXPOSURE_MIN = 16491
    PROP_AUTO_EXPOSURE_MAX = 16492
    PROP_AUTO_GAIN_MAX = 16493
    PROP_CONVERSION_GAIN_MODE = 16496
    PROP_AUTO_GAIN_ENABLED = 16497
    PROP_AUTO_BRIGHTNESS_MODE = 16498
    PROP_ZOOM = 16499
    PROP_IMAGE_PROCESS_TIME = 16500
    PROP_IMAGE_TRANSFER_TIME = 16501
    PROP_HOTPIXEL_CORRECTION_ENABLED = 16504
    PROP_HOTPIXEL_CORRECTION_FACTOR = 16505


class UCAPI_CCM(IntEnum):
    """PROP_COLOUR_TEMPERATURE enum indices on the K5C.

    Selects the host-side colour correction matrix applied after WB.
    IDENTITY (UserDefinedMatrix) is the identity to 0.6% (Phase 2 Stage 1,
    2026-08-06) — unity-WB idx0 captures are raw sensor signal. K5800 is the
    SDK default; all historical scans and cal tables live in that mixed
    space. Measured matrices: calibration/colorchecker_phase2_20260806/
    ccm_models.json.
    """

    IDENTITY = 0  # UserDefinedMatrix — no channel mixing
    K4500 = 1
    K5800 = 2  # SDK default
    K6600 = 3


class UCAPI_PIXEL_TYPE(IntEnum):
    """PROP_PIXEL_TYPE option values (ucapi.h 2023.3 PIXEL_TYPE enum).

    PROP_PIXEL_TYPE is an index (enum) property; its options carry these
    codes. The K5C default is PIXEL_TYPE_BGR (delivered frames); Bayer/mono
    values would bypass the host colour pipeline entirely.
    """

    PIXEL_TYPE_UNKNOWN = 0x00000000
    PIXEL_TYPE_INDEXED = 0x00000001
    PIXEL_TYPE_MONO = 0x00000002
    PIXEL_TYPE_RGB = 0x00000003
    PIXEL_TYPE_BGR = 0x00000004
    PIXEL_TYPE_BAYER_RG = 0x00000005
    PIXEL_TYPE_BAYER_GB = 0x00000006
    PIXEL_TYPE_BAYER_GR = 0x00000007
    PIXEL_TYPE_PACKED_FLAG = 0x20000000
    EXTENDED_PIXEL_TYPE_FLAG = 0x40000000
