"""Leica SDK enums.

Using IntEnum for type safety while maintaining compatibility with SDK int parameters.
Values from Leica AHM SDK 2020.3.3.10693.
"""

from enum import IntEnum


class TID(IntEnum):
    """Type IDs for microscope units."""

    # Core types
    MICROSCOPE = 4096
    MICROSCOPE_UNIT = 4097
    MICROSCOPE_MOTORIZED_UNIT = 4098
    MICROSCOPE_CODED_UNIT = 4099
    MICROSCOPE_MANUAL_UNIT = 4147

    # Axes
    MICROSCOPE_ZDRIVE = 4101
    MICROSCOPE_STAGE = 4112
    MICROSCOPE_X_UNIT = 4122
    MICROSCOPE_Y_UNIT = 4123
    MICROSCOPE_Z_UNIT = 4124

    # Optics
    MICROSCOPE_NOSEPIECE = 4100
    MICROSCOPE_IL_TURRET = 4104
    MICROSCOPE_CONDENSER = 4107
    MICROSCOPE_CONDENSER_TURRET = 4108
    MICROSCOPE_DIC_TURRET = 4116
    MICROSCOPE_PORTS = 4145

    # Illumination
    MICROSCOPE_LAMP = 4119
    MICROSCOPE_TL_LAMP = 4216
    MICROSCOPE_IL_LAMP = 4215
    MICROSCOPE_TL_AXIS = 4102
    MICROSCOPE_IL_AXIS = 4103
    MICROSCOPE_TL_IL_LAMP_SWITCH = 4120

    # Diaphragms
    MICROSCOPE_TL_APERTURE_DIAPHRAGM = 4140
    MICROSCOPE_TL_FIELD_DIAPHRAGM = 4141
    MICROSCOPE_IL_APERTURE_DIAPHRAGM = 4142
    MICROSCOPE_IL_FIELD_DIAPHRAGM = 4143
    MICROSCOPE_IL_ATTENUATOR = 4144

    # Shutters
    MICROSCOPE_SHUTTER = 4115
    MICROSCOPE_TL_SHUTTER = 4133
    MICROSCOPE_IL_SHUTTER = 4134

    # Focus
    MICROSCOPE_EXACT_ZFOCUS = 4247  # AFC
    MICROSCOPE_DVM_AUTOFOCUS = 4325

    # LED units
    MICROSCOPE_ARCLIGHT_UNIT = 4221
    MICROSCOPE_ARCLIGHT_INTENSITY = 4222
    MICROSCOPE_ARCLIGHT_SHUTTER = 4223
    MICROSCOPE_RINGLIGHT_UNIT = 4225
    MICROSCOPE_RINGLIGHT_INTENSITY = 4226
    MICROSCOPE_RINGLIGHT_SHUTTER = 4227

    # Light units
    MICROSCOPE_LIGHT_UNIT = 4181
    MICROSCOPE_ACTIVE_UNIT = 4294


class IID(IntEnum):
    """Interface IDs for unit capabilities."""

    # Core interfaces
    IID_DRIVER_INFO = 16
    IID_PROPERTIES = 260
    IID_EVENT_SOURCE = 262

    # Position control
    IID_BASIC_CONTROL_VALUE = 256
    IID_BASIC_CONTROL_VALUE_ASYNC = 269
    IID_DELTA_CONTROL_VALUE = 263
    IID_DELTA_CONTROL_VALUE_ASYNC = 283
    IID_DIRECTED_CONTROL_VALUE_ASYNC = 268
    IID_DIRECTED_CONTROL_VALUE_ASYNC_VELOCITY = 276

    # State and limits
    IID_BASIC_CONTROL_STATE = 266
    IID_HALT_CONTROL_VALUE = 267
    IID_LIMIT_CONTROL_VALUE = 265

    # Velocity/acceleration
    IID_BASIC_CONTROL_VALUE_VELOCITY = 264
    IID_BASIC_CONTROL_VALUE_ACCELERATION = 284

    # Calibration
    IID_AUTO_CALIBRATION = 258
    IID_DEFINED_CONTROL_VALUES = 272

    # Hysteresis
    IID_BASIC_CONTROL_VALUE_HYSTERESIS_CORRECTED = 281

    # Microscope-specific
    IID_MICROSCOPE_CONTRASTING_METHODS = 4096
    IID_MICROSCOPE_EXACT_ZFOCUS = 4119
    IID_MICROSCOPE_DVM_AUTOFOCUS = 4124


class EMetricsId(IntEnum):
    """Metrics IDs for unit conversion."""

    METRICS_NONE = 0
    METRICS_MICRONS = 1
    METRICS_VOLTAGE = 2
    METRICS_DIMENSIONLESS = 3
    METRICS_LIGHTYEARS = 4
    METRICS_MACH = 5
    METRICS_MICRONS_PER_SECOND = 6
    METRICS_DEGREES_KELVIN = 7
    METRICS_LINEPAIR_PER_MILLIMETERS = 8
    METRICS_DEGREES = 9
    METRICS_DEGREES_CELSIUS = 10
    METRICS_MICRONS_PER_SECOND_SQUARED = 11
    METRICS_NANOMETERS = 12
    METRICS_NATIVE = 13


class MoveState(IntEnum):
    """State of an async move operation."""

    PENDING = 0
    IN_PROGRESS = 1
    COMPLETE = 2
    CANCELLED = 3
    ERROR = 4
