"""Type definitions and protocols for Leica SDK objects.

These protocols define the expected interface of .NET objects returned by the SDK.
They're used for type hints only - the actual objects come from pythonnet.
"""

from typing import Protocol, Any


class UnitType(Protocol):
    """Protocol for SDK UnitType objects."""

    def IsA(self, type_id: int) -> bool: ...
    def ExposedTypeId(self) -> int: ...
    def NumTypeIds(self) -> int: ...
    def GetTypeId(self, index: int) -> int: ...


class Units(Protocol):
    """Protocol for SDK Units container."""

    def NumUnits(self) -> int: ...
    def GetUnit(self, index: int) -> "Unit": ...


class Interface(Protocol):
    """Protocol for SDK Interface wrapper."""

    def GetObject(self) -> Any: ...
    def GetInterfaceId(self) -> int: ...


class Interfaces(Protocol):
    """Protocol for SDK Interfaces container."""

    def FindInterface(self, iid: int) -> Interface | None: ...
    def HasInterface(self, iid: int) -> bool: ...
    def NumInterfaces(self) -> int: ...


class Unit(Protocol):
    """Protocol for SDK Unit objects."""

    def GetName(self) -> str: ...
    def GetUnitType(self) -> UnitType: ...
    def GetUnits(self) -> Units: ...
    def GetInterfaces(self) -> Interfaces: ...
    def GetParent(self) -> "Unit | None": ...
    def Dispose(self) -> None: ...
    def Init(self) -> None: ...


class MetricsConverter(Protocol):
    """Protocol for SDK MetricsConverter objects."""

    def GetMetricsValue(self, native_value: int) -> float: ...
    def GetControlValue(self, metrics_value: float) -> int: ...
    def GetMetricsId(self) -> int: ...


class MetricsConverters(Protocol):
    """Protocol for SDK MetricsConverters container."""

    def FindMetricsConverter(self, metrics_id: int) -> MetricsConverter | None: ...


class BasicControlValue(Protocol):
    """Protocol for SDK BasicControlValue interface."""

    def GetControlValue(self) -> int: ...
    def SetControlValue(self, value: int) -> None: ...
    def MinControlValue(self) -> int: ...
    def MaxControlValue(self) -> int: ...
    def GetMetricsConverters(self) -> MetricsConverters: ...


class AsyncResult(Protocol):
    """Protocol for SDK AsyncResult objects."""

    def GetState(self) -> int: ...
    def Dispose(self) -> None: ...


class BasicControlValueAsync(Protocol):
    """Protocol for SDK BasicControlValueAsync interface."""

    def SetControlValueAsync(self, value: int) -> AsyncResult: ...


class HaltControlValue(Protocol):
    """Protocol for SDK HaltControlValue interface."""

    def Halt(self) -> None: ...


class BasicControlState(Protocol):
    """Protocol for SDK BasicControlState interface."""

    def IsChanging(self) -> bool: ...


class BasicControlValueVelocity(Protocol):
    """Protocol for SDK BasicControlValueVelocity interface."""

    def GetVelocity(self) -> int: ...
    def SetVelocity(self, value: int) -> None: ...
    def MinVelocity(self) -> int: ...
    def MaxVelocity(self) -> int: ...


class AutoCalibration(Protocol):
    """Protocol for SDK AutoCalibration interface."""

    def IsCalibrated(self) -> bool: ...
    def Calibrate(self) -> None: ...


class EventSource(Protocol):
    """Protocol for SDK EventSource interface."""

    def Subscribe(self, handler: Any) -> None: ...
    def Subscribe2(self, handler: Any) -> None: ...
    def UnSubscribe(self, handler: Any) -> None: ...
    def UnSubscribe2(self, handler: Any) -> None: ...


class HardwareModel(Protocol):
    """Protocol for SDK HardwareModel singleton."""

    def GetUnit(self, name: str) -> Unit: ...
    def Dispose(self) -> None: ...


# ============================================================================
# UCAPI (Camera) Protocols
# ============================================================================


class ImageFormat(Protocol):
    """Protocol for SDK ImageFormat objects."""

    def Width(self) -> int: ...
    def Height(self) -> int: ...
    def PixelBufferSize(self) -> int: ...
    def Stride(self) -> int: ...


class Image(Protocol):
    """Protocol for SDK Image objects."""

    def Format(self) -> ImageFormat: ...
    def PixelData(self) -> Any: ...  # IntPtr
    def LockPixelData(self) -> None: ...
    def UnlockPixelData(self) -> None: ...
    def Dispose(self) -> None: ...


class ImageAcquisitionContext(Protocol):
    """Protocol for SDK ImageAcquisitionContext."""

    @property
    def IsCancelled(self) -> bool: ...
    @IsCancelled.setter
    def IsCancelled(self, value: bool) -> None: ...
    @property
    def ImageAcquiredHandler(self) -> Any: ...
    @ImageAcquiredHandler.setter
    def ImageAcquiredHandler(self, handler: Any) -> None: ...
    def Dispose(self) -> None: ...


class ImageAcquisition(Protocol):
    """Protocol for SDK ImageAcquisition interface."""

    def Acquire(self, context: ImageAcquisitionContext, prop_ids: Any) -> None: ...
    def AcquireContinuous(self, context: ImageAcquisitionContext, prop_ids: Any) -> None: ...


class PropertyValue(Protocol):
    """Protocol for SDK PropertyValue objects."""

    def GetValue(self) -> Any: ...
    def SetValue(self, value: Any) -> None: ...
    def GetIndex(self) -> int: ...
    def SetIndex(self, index: int) -> None: ...


class Property(Protocol):
    """Protocol for SDK Property objects."""

    def GetId(self) -> int: ...
    def GetValue(self) -> PropertyValue: ...


class Properties(Protocol):
    """Protocol for SDK Properties interface."""

    def FindProperty(self, prop_id: int) -> Property | None: ...
    def NumProperties(self) -> int: ...
    def GetProperty(self, index: int) -> Property: ...
